exports.BANK =  [
    {value: "", label: "Không có"},
    { value: "AGB",label: 'Agribank'},
    { value: "BIDV",label:  'BIDV' },
    { value: "VCB",label:  'Vietcombank' },
    { value: "BAB",label:  'Bac A Bank' },
    { value: "EXB",label:  'Eximbank' },
    { value: "MSB",label:  'MariTimeBank' },
    { value: "STB",label:  'Sacombank' },
    { value: "SGB",label:  'Saigon Công Thương' },
    { value: "NVB",label:  'Quốc Dân' },
    { value: "PGB",label:  'PGBank' },
    { value: "GPB",label:  'GPBank'},
    { value: "ICB",label:  'Vietinbank' },
    { value: "TCB",label:  'Techcombank' },
    { value: "TPB",label:  'TienPhongBank' },
    { value: "VAB",label:  'VietABank' },
    { value: "VIB",label:  'VIB' },
    { value: "DAB",label:  'DongABank' },
    { value: "MB",label:  'MB Bank' },
    { value: "ACB",label:  'ACB' },
    { value: "HDB",label:  'HDBank' },
    { value: "VPB",label:  'VPBank' },
    { value: "OJB",label:  'Oceanbank '},
    { value: "SHB",label:  'SHB' },
    { value: "NAB",label:  'NamABank' },
    { value: "PVCOMBANK",label:  'Đại Chúng Việt Nam' },
]
